logging.config: classpath:log4j2-spring-dev.xml

spring:
  config:
    import:
      - ./actuator/app-dev-actuator.yml
      - ./mail/app-dev-mail.yml
      
app:
  info:
    environment: ${spring.profiles.active}
