logging.config: classpath:log4j2-spring-uat.xml

spring:
  devtools:
    livereload:
      enabled: false
  config:
    import:
      - ./actuator/app-uat-actuator.yml
      - ./gateway/app-uat-gateway.yml

app:
  info:
    environment: ${spring.profiles.active}
