logging.config: classpath:log4j2-spring-prod.xml

spring:
  devtools:
    livereload:
      enabled: false
  config:
    import:
      - ./actuator/app-prod-actuator.yml
      - ./gateway/app-prod-gateway.yml
      
app:
  info:
    environment: ${spring.profiles.active}
