logging.config: classpath:log4j2-spring-uat.xml

spring:
  devtools:
    livereload:
      enabled: false
  config:
    import:
      - ./actuator/app-uat-actuator.yml
      - ./api/app-uat-api.yml

app:
  info:
    environment: ${spring.profiles.active}
