logging.config: classpath:log4j2-spring-local.xml

spring:
  config:
    import:
      - ./actuator/app-local-actuator.yml
      - ./api/app-local-api.yml
      
app:
  info:
    environment: ${spring.profiles.active}
