server:
  port: 9002
  netty:
    connection-timeout: 2s
  shutdown: graceful # Enables the graceful shutdown feature
    # Netty uses an Event Loop model, so you don't typically 
    # configure "min-spare" or "max" threads like Tomcat.

spring:
  webflux:
   base-path: /payment-service			 # This is the reactive equivalent of context-path. http://localhost:9002/payment-service/swagger-ui.html
  application:
    name: payment-service
  lifecycle:
    timeout-per-shutdown-phase: 30s # Max time to wait for requests to finish
  profiles:
    active: '@spring.profiles.active@'
  threads:
    virtual:
      enabled: true
  devtools:
    livereload:
      enabled: true
  config:
    import:
      - ./actuator/app-actuator.yml
      - ./api/app-api.yml
      - ./i18n/i18n.yml
      - ./jackson/app-jackson.yml
      - ./resilience4j/app-resillience4j.yml
      - ./spring-doc/app-spring-doc.yml

      
      
  
